let name;
let lastname;
let group;
let yearOfBearth;
name = "Vadym";
lastname = "Drenkaliuk";
group = "JS QC";
yearOfBirth = 1991;
let isMarried = false;
typeof(name);
typeof(lastname);
typeof(group);
typeof(yearOfBirth);
typeof(isMarried);
console.log(yearOfBirth, isMarried, name, lastname, group);
const typeIsNull = null;
let typeIsUndefined;
console.log(typeof(typeIsNull), typeof(typeIsUndefined));